### ISSUE TITLE
unbound variable on macos ventura

### ISSUE THREAD

**Issue by luis-echegaray** [nickjj/docker-flask-example#12]
❯ ./run quality
./run: line 55: @: unbound variable

❯ ./run lint:dockerfile
./run: line 44: @: unbound variable

Solution

```brew install bash```

this currently takes you from:
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)
to
GNU bash, version 5.2.2(1)-release (aarch64-apple-darwin22.1.0)

**Comment by nickjj** [comment]
Hi,

Thanks. I have noticed this too and can reproduce the behavior.

This stems from setting `set -o nounset` near the top of the `run` script.

I haven't been able to figure out a good solution to this that doesn't make things super convoluted. I'm open for suggestions if anyone has them.

**Comment by nickjj** [comment]
Since then I've removed that option since it fails out of the box on macOS.
