### ISSUE TITLE
remove asset in .env file and request is slowly

### ISSUE THREAD

**Issue by JLTG2018** [nickjj/docker-flask-example#14]
When I remove asset in .env file,  and then start the docker-compose, the request is very slow, Could you tell me how can I fix this problem

**Comment by nickjj** [comment]
Hi,

I'm not sure, I would need more details.

Can you repeat it 100% of the time? Can you record a video demonstrating it multiple times in a row? How did you install Docker? What version of Docker do you have? What OS are you using? If you're using Windows are you using PowerShell or WSL or WSL 2?

**Comment by nickjj** [comment]
I'm going to close this one as there's no response and I haven't seen this come up in a bunch of projects based off this on different boxes and operating systems (both dev and prod).
