### ISSUE TITLE
models usage

### ISSUE THREAD

**Issue by nhjiejan** [nickjj/docker-flask-example#18]
Hi,

How can i define models, create tables and interact with the data with this setup? slightly confused as you've added a seeds.py but no template models

**Comment by nickjj** [comment]
Hi,

You can use whatever model structure you'd like using SQLAlchemy.

It wouldn't make sense in this case but let's say you had models associated with the `up` blueprint, you could drop a `models.py` file in that directory and do whatever you need to do.
