### ISSUE TITLE
In file ./.env: environment variable name 'export COMPOSE_PROJECT_NAME' may not contain whitespace.

### ISSUE THREAD

**Issue by simin75simin** [nickjj/docker-flask-example#2]
resulted from running docker-compose up --build after following the steps
OS: ubuntu18.04
Docker version 19.03.13, build cd8016b6bc

**Comment by nickjj** [comment]
Hi,

What version of Docker Compose do you have? You can check with `docker-compose --version`.

It sounds like you might have an old version (years old) which doesn't support `export `, but I think 1.26+ supports that.

**Comment by nickjj** [comment]
Going to close this as there's a 99.9% chance is the case.

After you update Docker Compose to 1.26+ if it doesn't work feel free to respond back here.
