### ISSUE TITLE
Deprecated library distutils

### ISSUE THREAD

**Issue by Car85** [nickjj/docker-flask-example#23]
Hello @nickjj,

Thank you so much for sharing this repository with the community.

When cloning your repo locally, I noticed that distutils is not included in the latest versions of Python.

![image](https://github.com/nickjj/docker-flask-example/assets/170861775/92661746-cea3-4036-8531-0f9bb4a12a31)

Do you have any alternatives in mind?

Thanks again for your work.

**Comment by nickjj** [comment]
Docker recently removed this package from their Python image, that's how it was available previously.

I explicitly added it in this commit: https://github.com/nickjj/docker-flask-example/commit/ba0e05f3f91f71080fffba95a8880b9f22cce058
